In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
import os
import tensorflow as tf
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [5]:
import torch

In [8]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [9]:
torch.cuda.is_available()

True

# Intro to Deep Learning

## Live Demo

In [12]:
# python basic operation
a = 10
b = 15
# result is of type int
(3 * a + 4 * b) ** 2

8100

In [14]:
# python list manipulation similar to numpy
a = [10, 17, 28, 13, 12]
b = [22, 12, 55, 11, 7]
# result is type list
[(3 * x + 4 * y) for x, y in zip(a, b)]

[118, 99, 304, 83, 64]

In [17]:
# numpy version with vectorization
a = np.array([10, 17, 28, 13, 12])
b = np.array([22, 12, 55, 11, 7])
print((3 * a + 4 * b) ** 2)
print(type((3 * a + 4 * b) ** 2))

[13924  9801 92416  6889  4096]
<class 'numpy.ndarray'>


In [21]:
# tensorflow version
a = tf.constant([10, 17, 28, 13, 12])
b = tf.constant([22, 12, 55, 11, 7])
print((3 * a + 4 * b) ** 2)
print(type((3 * a + 4 * b) ** 2))

tf.Tensor([13924  9801 92416  6889  4096], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [22]:
# torch version
a = torch.tensor([10, 17, 28, 13, 12])
b = torch.tensor([22, 12, 55, 11, 7])
print((3 * a + 4 * b) ** 2)
print(type((3 * a + 4 * b) ** 2))

tensor([13924,  9801, 92416,  6889,  4096])
<class 'torch.Tensor'>


In [30]:
# if we want to pass a clean python function to tensorflow, we decorate it (tensorflow 2.)
def tf_input_decorator(func):
    def wrapper(*args, **kwargs):
        # Convert all positional arguments to tensors
        tf_args = [tf.convert_to_tensor(arg) for arg in args]
        # Convert all keyword arguments to tensors
        tf_kwargs = {key: tf.convert_to_tensor(value) for key, value in kwargs.items()}
        # Call the original function with TensorFlow objects
        return func(*tf_args, **tf_kwargs)
    return wrapper

In [ ]:
@tf_input_decorator
def my_func(a, b):
    return (3 * a + 4 * b) ** 2

In [31]:
a = 10, 17, 28, 13, 12]
b = [22, 12, 55, 11, 7]
my_func(a, b)

SyntaxError: unmatched ']' (835591254.py, line 1)