In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.optim import SGD

import numpy as np

In [2]:
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.input_layer = nn.Linear(in_features=4, out_features=8)
        self.hidden_layer = nn.Linear(in_features=8, out_features=8)
        self.output_layer = nn.Linear(in_features=8, out_features=2)

    def forward(self, x):
        x = F.relu(self.input_layer(x))
        x = F.relu(self.hidden_layer(x))

        return self.output_layer(x)

In [3]:
layer = nn.Linear(4, 8) # layer of 8 neurons, expecting 4 parameters as input and producing 8 as output
layer.state_dict()

OrderedDict([('weight',
              tensor([[ 0.0784,  0.2568, -0.3510, -0.3783],
                      [ 0.0500, -0.1831, -0.0201, -0.0686],
                      [-0.1565, -0.4479,  0.2917,  0.4173],
                      [ 0.4897, -0.1754,  0.1121, -0.4862],
                      [ 0.4567, -0.4190,  0.1325,  0.0752],
                      [ 0.3842,  0.3238, -0.2118, -0.2044],
                      [-0.1129,  0.4409,  0.1430,  0.4510],
                      [-0.3169,  0.4159, -0.4186,  0.3631]])),
             ('bias',
              tensor([-0.2212,  0.3928,  0.4156,  0.2701, -0.2840,  0.3283,  0.0881, -0.3233]))])

In [4]:
tens = torch.randn(1, 4) # creating random tensor of 1 row (observation) with 4 parameteres each

In [5]:
tens

tensor([[-0.9074,  0.5442, -2.1147, -0.6949]])

In [6]:
layer(tens) 

tensor([[ 0.8525,  0.3380, -0.5930, -0.1689, -1.2588,  0.7459, -0.1854,  0.8235]],
       grad_fn=<AddmmBackward0>)

In [7]:
simple_nn = SimpleNN()

In [8]:
simple_nn(tens)

tensor([[ 0.3096, -0.2131]], grad_fn=<AddmmBackward0>)

In [9]:
obs = 400
input_params = 4
output_params = 2
x_train = torch.randn(obs, input_params)
y_train = torch.randn(obs, output_params)

In [10]:
simple_nn.training

True

In [11]:
simple_nn.state_dict().keys()

odict_keys(['input_layer.weight', 'input_layer.bias', 'hidden_layer.weight', 'hidden_layer.bias', 'output_layer.weight', 'output_layer.bias'])

In [12]:
next(simple_nn.parameters())

Parameter containing:
tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
        [-0.3996,  0.1414,  0.4794,  0.3626],
        [ 0.3707, -0.1956, -0.0176,  0.1580],
        [ 0.0500, -0.0808,  0.1630, -0.1882],
        [-0.0765,  0.3600,  0.2809,  0.1913],
        [ 0.3630, -0.1355, -0.0041,  0.3677],
        [ 0.1558,  0.0772, -0.2624,  0.1229],
        [ 0.2055, -0.0991,  0.0067,  0.1187]], requires_grad=True)

In [13]:
next(simple_nn.output_layer.parameters())

Parameter containing:
tensor([[-0.1035,  0.0631,  0.0301,  0.3241,  0.2538, -0.1636, -0.0126,  0.1170],
        [ 0.0572, -0.0795, -0.2737,  0.1933, -0.2509, -0.1715, -0.0970,  0.3505]],
       requires_grad=True)

In [14]:
tens

tensor([[-0.9074,  0.5442, -2.1147, -0.6949]])

In [15]:
next(simple_nn.parameters())

Parameter containing:
tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
        [-0.3996,  0.1414,  0.4794,  0.3626],
        [ 0.3707, -0.1956, -0.0176,  0.1580],
        [ 0.0500, -0.0808,  0.1630, -0.1882],
        [-0.0765,  0.3600,  0.2809,  0.1913],
        [ 0.3630, -0.1355, -0.0041,  0.3677],
        [ 0.1558,  0.0772, -0.2624,  0.1229],
        [ 0.2055, -0.0991,  0.0067,  0.1187]], requires_grad=True)

In [16]:
simple_nn.input_layer.state_dict()

OrderedDict([('weight',
              tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
                      [-0.3996,  0.1414,  0.4794,  0.3626],
                      [ 0.3707, -0.1956, -0.0176,  0.1580],
                      [ 0.0500, -0.0808,  0.1630, -0.1882],
                      [-0.0765,  0.3600,  0.2809,  0.1913],
                      [ 0.3630, -0.1355, -0.0041,  0.3677],
                      [ 0.1558,  0.0772, -0.2624,  0.1229],
                      [ 0.2055, -0.0991,  0.0067,  0.1187]])),
             ('bias',
              tensor([ 0.4602, -0.2159,  0.2743, -0.3012,  0.1277, -0.1782, -0.2866, -0.2593]))])

In [17]:
simple_nn.state_dict().keys()

odict_keys(['input_layer.weight', 'input_layer.bias', 'hidden_layer.weight', 'hidden_layer.bias', 'output_layer.weight', 'output_layer.bias'])

In [18]:
simple_nn.state_dict()['input_layer.weight']

tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
        [-0.3996,  0.1414,  0.4794,  0.3626],
        [ 0.3707, -0.1956, -0.0176,  0.1580],
        [ 0.0500, -0.0808,  0.1630, -0.1882],
        [-0.0765,  0.3600,  0.2809,  0.1913],
        [ 0.3630, -0.1355, -0.0041,  0.3677],
        [ 0.1558,  0.0772, -0.2624,  0.1229],
        [ 0.2055, -0.0991,  0.0067,  0.1187]])

In [19]:

simple_nn.input_layer.weight

Parameter containing:
tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
        [-0.3996,  0.1414,  0.4794,  0.3626],
        [ 0.3707, -0.1956, -0.0176,  0.1580],
        [ 0.0500, -0.0808,  0.1630, -0.1882],
        [-0.0765,  0.3600,  0.2809,  0.1913],
        [ 0.3630, -0.1355, -0.0041,  0.3677],
        [ 0.1558,  0.0772, -0.2624,  0.1229],
        [ 0.2055, -0.0991,  0.0067,  0.1187]], requires_grad=True)

In [20]:
y_pred = simple_nn(tens)

In [21]:
y_pred

tensor([[ 0.3096, -0.2131]], grad_fn=<AddmmBackward0>)

In [22]:
y_true = torch.tensor([[0.5, 0.5]])

In [23]:
y_true

tensor([[0.5000, 0.5000]])

In [24]:
mse_error = np.mean([y_pred.detach() - y_true]) ** 2

In [25]:
mse_error

np.float32(0.2040921)

In [26]:
(((-0.0892 - 0.5) + (-0.0416 - 0.5)) / 2) ** 2

0.3196771599999999

In [27]:
simple_nn.state_dict()

OrderedDict([('input_layer.weight',
              tensor([[-0.4677, -0.3585, -0.4568, -0.3508],
                      [-0.3996,  0.1414,  0.4794,  0.3626],
                      [ 0.3707, -0.1956, -0.0176,  0.1580],
                      [ 0.0500, -0.0808,  0.1630, -0.1882],
                      [-0.0765,  0.3600,  0.2809,  0.1913],
                      [ 0.3630, -0.1355, -0.0041,  0.3677],
                      [ 0.1558,  0.0772, -0.2624,  0.1229],
                      [ 0.2055, -0.0991,  0.0067,  0.1187]])),
             ('input_layer.bias',
              tensor([ 0.4602, -0.2159,  0.2743, -0.3012,  0.1277, -0.1782, -0.2866, -0.2593])),
             ('hidden_layer.weight',
              tensor([[-0.1551,  0.2934, -0.2483, -0.3033,  0.0997, -0.2500, -0.1236, -0.1987],
                      [-0.2636, -0.3243, -0.2588,  0.2505,  0.2785,  0.0157,  0.3439,  0.1861],
                      [-0.3178, -0.1065, -0.3139,  0.2254,  0.2761, -0.3377,  0.1439,  0.3229],
                      [ 0

In [28]:
y_true = torch.randn((obs, output_params))

In [29]:
params = simple_nn.input_layer(tens)

In [30]:
params.clamp(0)

tensor([[1.8992, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0836, 0.0000]],
       grad_fn=<ClampBackward1>)

In [31]:
optim = SGD(simple_nn.parameters(), lr=3e-4)

In [32]:
y_pred

tensor([[ 0.3096, -0.2131]], grad_fn=<AddmmBackward0>)

In [44]:
class Bias:
    def __init__(self, h_size: int) -> None:
        self._h_size = h_size
        self._value = None
        
    @property
    def value(self):
        if self._value is None:
            self._value = self._generate_value()

        return self._value

    def _generate_value(self):
        return np.random.uniform(-0.5, 0.5, size=(1, self._h_size))


    def __call__(self):
        return self.value

    def __repr__(self):
        return str(self.__dict__)

class Weight:
    def __init__(self, v_size: int, h_size: int):
        self._v_size = v_size
        self._h_size = h_size
        self._value = None

    
    @property
    def value(self):
        if self._value is None:
            self._value = self._generate_value()

        return self._value

    def _generate_value(self):
        return np.random.uniform(-0.5, 0.5, size=(self._v_size, self._h_size))

    def __call__(self):
        return self.value

    def __repr__(self):
        return str(self.__dict__)
                   
class LinearLayer:
    def __init__(self, _input: int, _output: int, require_grad=True):
        self._input = _input
        self._output = _output
        self._bias = Bias(_output)()
        self._weights = Weight(_input, _output)()
        self._require_grad = require_grad
        self._last_input = None  # Store input for gradient calculation
        self._last_output = None  # Store output before activation
    
    @property
    def state_dict(self):
        return dict(
            weights = self._weights,
            bias = self._bias,
        )

    def forward(self, x, track_fn):
        """ Linear transformation + tracking """
        self._last_input = x  # Store input for backprop
        self._last_output = np.dot(x, self._weights) + self._bias  # Linear output
        track_fn.append("linear")  # Track function application in global list
        return self._last_output


    def __call__(self, track_fn, x=None):
        if x is None:
            return self.state_dict
        else:
            return self.forward(x, track_fn)

    def __repr__(self):
        return str(self.state_dict)
        

def relu_activation(layer, track_fn):
    """ Applies ReLU activation function and tracks it """
    track_fn.append("relu")  # Track ReLU function for backprop
    return np.clip(layer, 0, np.inf)


class NeuralNetwork:

    @property
    def state_dict(self):
        return self.__dict__

    def forward(sefl, x):
        raise NotImplementedError('The forward() method must be implemented')

    def __call__(self, x):
        return self.forward(x)

class CustomNeuralNetwork(NeuralNetwork):
    def __init__(self):
        self.input_layer = LinearLayer(2, 4)
        self.hidden_layer = LinearLayer(4, 4)
        self.output_layer = LinearLayer(4, 2)

        # Store forward pass function tracking
        self._grad_fn = []

    def forward(self, x):
        x = relu_activation(self.input_layer(self._grad_fn, x), self._grad_fn)
        x = relu_activation(self.hidden_layer(self._grad_fn, x), self._grad_fn)
        x = self.output_layer(self._grad_fn, x)
        return x

    def backward(self, y_true):

        def calculate_total_loss(y_pred, y_true):
            return np.sum((y_pred - y_true) ** 2) / y_true.size
        
        # compute loss gradient
        y_pred = self.forward(x)
        dl_dY = 2 * (y_pred - y_true) / y_true.size

        # backpropagete loss to output layer linear
        
        # backpropagete loss to relu of output layer
        # backpropagete loss to hidden layer linear
        # backproapagete loss to relu of hidden layer
        # backpropaget loss to input layer linear

    def track_functions(self):
        return self._grad_fn  # Returns list of applied functions for backprop tracking
    
    def __repr__(self):
        return self.state_dict

In [51]:
large_input = np.random.randn(1, 2)

In [52]:
y_true = np.random.randn(1, 2)

In [53]:
nnetwork = CustomNeuralNetwork()

In [54]:
y_pred = nnetwork(large_input)

In [48]:
nnetwork.track_functions()

['linear', 'relu', 'linear', 'relu', 'linear']

In [49]:
layer = LinearLayer(2, 3)

In [39]:
layer.state_dict

{'weights': array([[ 0.46125283,  0.34947476, -0.31806412],
        [ 0.3562043 ,  0.43119667, -0.19698812]]),
 'bias': array([[ 0.191104  ,  0.44145165, -0.44871332]])}

In [56]:
print(large_input)
print(y_pred)
print(y_true)

[[ 1.38989888 -0.03148645]]
[[0.17516494 0.38806318]]
[[-0.69922791  1.01859117]]


In [57]:
np.sum((y_pred - y_true) ** 2) / y_true.size

np.float64(0.5810641942631614)

In [59]:
nnetwork.state_dict.keys()

dict_keys(['input_layer', 'hidden_layer', 'output_layer', '_grad_fn'])